name: Deploy to Tomcat on rasppi

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: self-hosted
    
    env:
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TARGET: ${{ secrets.EMAIL_TARGET }}

    
     



    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Debug Environment Variables
      run: |
        echo "EMAIL_HOST: $EMAIL_HOST"
        echo "EMAIL_PORT: $EMAIL_PORT"
        echo "EMAIL_USERNAME: $EMAIL_USERNAME"
        echo "EMAIL_TARGET: $EMAIL_TARGET"
        echo "TOMCAT_URL: $TOMCAT_URL"

        
    - name: Build with Maven
      run: mvn package -DskipTests -X
     
    - name: Deploy to Tomcat
      env:
        TOMCAT_URL: ${{ secrets.TOMCAT_URL }}
        TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
      run: |
        curl -u $TOMCAT_USER:$TOMCAT_PASSWORD "http://$TOMCAT_URL/manager/text/undeploy?path=/"
        curl -u $TOMCAT_USER:$TOMCAT_PASSWORD --upload-file target/Centralized-Web-Application-4.0.war "http://$TOMCAT_URL/manager/text/deploy?path=/"
